DROP TABLE IF EXISTS cliente CASCADE;
CREATE TABLE cliente (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cpf VARCHAR(14),
    nome VARCHAR(255),
    email VARCHAR(255),
    telefone VARCHAR(20),
    logradouro VARCHAR(100),
    bairro VARCHAR(100),
    cidade VARCHAR(50),
    uf CHAR(2),
    cep CHAR(9)
);

DROP TABLE IF EXISTS categoria CASCADE;
CREATE TABLE categoria (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(100)
);

DROP TABLE IF EXISTS produto CASCADE;
CREATE TABLE produto (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(100),
    preco DECIMAL(10,2),
    descricao VARCHAR(1000)
    quantidade_em_estoque INT NOT NULL,
    categoria_id BIGINT NOT NULL,
    FOREIGN KEY (categoria_id) REFERENCES categoria (id)
);

DROP TABLE IF EXISTS categoria_produto CASCADE;